sonata_user:
    profile:
        # Profile show page is a dashboard as in SonataAdminBundle
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
                 # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_show', label: 'Perfil', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'Edita tu perfil', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'Cambia la contraseña', domain: 'SonataUserBundle'}
            - { route: 'fos_user_security_logout', label: 'Salir', domain: 'SonataUserBundle'}